ModongModong/modongmodong

- frontend/type2/client/src/App.jsx
- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/Add_post.module.css
> feat:게시판 등록페이지 구현

- backend/server/build.gradle
- backend/server/src/main/java/org/example/server/controllers/ApiController.java
- backend/server/src/main/java/org/example/server/controllers/PostController.java
- backend/server/src/main/java/org/example/server/domain/Comment.java
- backend/server/src/main/java/org/example/server/domain/Post.java
- backend/server/src/main/java/org/example/server/dto/CommentRequestDto.java
- backend/server/src/main/java/org/example/server/dto/CommentResponseDto.java
- backend/server/src/main/java/org/example/server/dto/PostRequestDto.java
- backend/server/src/main/java/org/example/server/dto/PostResponseDto.java
- backend/server/src/main/java/org/example/server/entities/Comment.java
- backend/server/src/main/java/org/example/server/entities/Post.java
- backend/server/src/main/java/org/example/server/repository/CommentRepository.java
- backend/server/src/main/java/org/example/server/repository/PostRepository.java
- backend/server/src/main/java/org/example/server/service/CommentService.java
- backend/server/src/main/java/org/example/server/service/PostService.java
- backend/server/src/main/resources/application.properties
급하게 머지 후 추후에 버그수정과 리팩토링 예정입니다.
> feat: 메인화면 게시판,댓글 REST API 구현

- backend/server/src/main/java/org/example/server/controllers/CommentController.java
- backend/server/src/main/java/org/example/server/service/CommentService.java
> 파일 구조 수정 2

- frontend/type2/client/src/PetRegister/PetRegistrationForm.jsx
> refactor: 뒤로가기핸들러 수정

- backend/.idea/misc.xml
- backend/.idea/modules.xml
- backend/server/src/main/java/org/example/server/controllers/CommentController.java
- backend/server/src/main/java/org/example/server/controllers/PostController.java
- backend/server/src/main/java/org/example/server/dto/CommentRequestDto.java
- backend/server/src/main/java/org/example/server/dto/CommentResponseDto.java
- backend/server/src/main/java/org/example/server/dto/PostRequestDto.java
- backend/server/src/main/java/org/example/server/dto/PostResponseDto.java
- backend/server/src/main/java/org/example/server/entities/Comment.java
- backend/server/src/main/java/org/example/server/entities/Post.java
- backend/server/src/main/java/org/example/server/repository/CommentRepository.java
- backend/server/src/main/java/org/example/server/service/CommentService.java
- backend/server/src/main/java/org/example/server/service/PostService.java
> rest api 테스트 완료 코드 수정

- frontend/type2/client/index.html
- frontend/type2/client/src/App.jsx
- frontend/type2/client/src/assets/FloatingBtn/Floating_btn.jsx
- frontend/type2/client/src/common/Navigation/Navigation.jsx
- frontend/type2/client/src/main.jsx
- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/Home.jsx
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/src/page/Search/Search_pharmacy.jsx
- frontend/type2/client/src/page/Search/Search_pharmacy.module.css
> fix-페이지간 연결

- frontend/type2/client/src/page/Home/PostDelete.jsx
- frontend/type2/client/src/page/Home/PostDelete.module.css
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/src/page/Home/PostDetail.module.css
> 삭제 모달창 추가, 수정페이지(미완성) 커밋

- frontend/type2/client/src/App.jsx
- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/Home.jsx
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/vite.config.js
> feat-게시글 get api연결

- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/Home.jsx
- frontend/type2/client/src/page/Home/PostDetail.jsx
상세페이지 api 연결 중간완료하였습니다
1. 상세페이지 불러오기
2. 페이지 삭제하기
> feat-상세페이지 api연결 (중간완료)

- backend/server/src/main/java/org/example/server/controllers/CommentController.java
- backend/server/src/main/java/org/example/server/controllers/PostController.java
- backend/server/src/main/java/org/example/server/service/CommentService.java
- backend/server/src/main/java/org/example/server/service/PostService.java
1.  컨트롤러 @PathVariable() 값 수정
2. 게시물 좋아요 취소 추가
3. 댓글 좋아요, 싫어요 취소 추가
> feat-댓글-좋아요-싫어요-취소-구현 

- frontend/type2/client/src/page/Home/Home.jsx
> fix-타임스탬프 기능 추가

- backend/server/build.gradle
- backend/server/src/main/java/org/example/server/entities/User.java
- backend/server/src/main/java/org/example/server/repository/UserRepository.java
- backend/server/src/main/java/org/example/server/service/UserDetailService.java
> feat: backend users 수정

- backend/server/src/main/java/org/example/server/config/WebSecurityConfig.java
- backend/server/src/main/java/org/example/server/controllers/UserApiController.java
- backend/server/src/main/java/org/example/server/controllers/UserViewController.java
- backend/server/src/main/java/org/example/server/dto/AddUserRequest.java
- backend/server/src/main/java/org/example/server/dto/AddUserResponse.java
- backend/server/src/main/java/org/example/server/dto/LoginRequest.java
- backend/server/src/main/java/org/example/server/dto/LoginResponse.java
- backend/server/src/main/java/org/example/server/entities/User.java
- backend/server/src/main/java/org/example/server/service/UserService.java
- frontend/type2/client/src/login/jsx/login.jsx
- frontend/type2/client/src/login/jsx/signup.jsx
> Feat login db 연동

- backend/server/src/main/java/org/example/server/controllers/PetController.java
- backend/server/src/main/java/org/example/server/dto/PetResponseDto.java
- backend/server/src/main/java/org/example/server/repository/PetRepository.java
- backend/server/src/main/java/org/example/server/service/PetService.java
> feat: 반려동물수정, 마이페이지 동물목록조회 api

- backend/server/src/main/java/org/example/server/controllers/UserApiController.java
- backend/server/src/main/java/org/example/server/entities/User.java
- frontend/type2/client/src/MyPage/MyPage.jsx
- frontend/type2/client/src/login/css/login.module.css
- frontend/type2/client/src/login/css/signup.module.css
- frontend/type2/client/src/login/jsx/login.jsx
- frontend/type2/client/src/login/jsx/signup.jsx
fix: front-css,jsx 수정 / Backend-유저 정보 수정
> Fix login css 수정

- frontend/type2/client/src/App.jsx
- frontend/type2/client/src/assets/FloatingBtn/FloatingBtn.module.css
- frontend/type2/client/src/page/Home/Home.jsx
- frontend/type2/client/src/page/Home/Home.module.css
> fix-메인페이지 모바일사이즈로 변경

- frontend/type2/client/src/login/jsx/login.jsx
- frontend/type2/client/src/login/jsx/signup.jsx
login 아이디 -> 이메일 수정
로그인 후 메인화면으로 이동
> Fix login 짜잘짜잘

- frontend/type2/client/src/login/jsx/signup.jsx
> Fix login 짜잘짜잘2

- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/Add_post.module.css
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/src/page/Home/PostDetail.module.css
- frontend/type2/client/src/page/Search/Search_pharmacy.module.css
게시글페이지(상세페이지, 페이지 등록, 페이지 삭제) 모바일 버전으로 사이즈 변경
게시글 좋아요 api 연결
상세 페이지의 댓글 입력 인풋 구현
댓글 조회 api 연결
> fix-게시글페이지:모바일사이즈로수정, api연결

- backend/server/src/main/java/org/example/server/controllers/CommentController.java
- backend/server/src/main/java/org/example/server/dto/CommentRequestDto.java
- backend/server/src/main/java/org/example/server/dto/CommentResponseDto.java
- backend/server/src/main/java/org/example/server/service/CommentService.java
- frontend/type2/client/src/page/Home/PostDetail.jsx
> fix 게시판 댓글 관련 수정

- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/src/page/Home/PostDetail.module.css
- frontend/type2/client/src/page/Home/Update_post.jsx
> 1. 댓글 기능 구현

- backend/server/src/main/java/org/example/server/controllers/PetController.java
- frontend/type2/client/src/PetRegister/PetModificationForm.jsx
- frontend/type2/client/src/PetRegister/PetRegistrationForm.jsx
수정페이지에서 중성화여부가 get되지 않는 오류 있음
폼 제출 버튼을 클릭하면 /login 무한 리다이렉트 발생함
> Feat 반려동물수정api fetch

- frontend/type2/client/src/App.jsx
- frontend/type2/client/src/NsRecommendation/NsRecommendation.jsx
- frontend/type2/client/src/common/Navigation/Navigation.jsx
> feat: 영양제api-fetch

- frontend/type2/client/src/login/css/ErrorPopup.module.css
- frontend/type2/client/src/login/jsx/ErrorPopup.jsx
- frontend/type2/client/src/login/jsx/login.jsx
- frontend/type2/client/src/login/jsx/signup.jsx
> fix: login-popup setting

- backend/server/src/main/java/org/example/server/controllers/NsController.java
- backend/server/src/main/java/org/example/server/controllers/PetController.java
- backend/server/src/main/java/org/example/server/dto/NsResponseDto.java
- backend/server/src/main/java/org/example/server/dto/PetRequestDto.java
- backend/server/src/main/java/org/example/server/dto/PetResponseDto.java
- backend/server/src/main/java/org/example/server/entities/Pet.java
- backend/server/src/main/java/org/example/server/service/NsService.java
- backend/server/src/main/java/org/example/server/service/PetService.java
- frontend/type2/client/src/PetRegister/PetModificationForm.jsx
수정 api는 값에서만 작동이 됨, 드롭다운은 작동안됨
등록 api에서 오류가 난다
> Fix: 반려동물, 영양제 api 수정

- frontend/type2/client/src/page/Home/Add_post.jsx
- frontend/type2/client/src/page/Home/MainModal.jsx
- frontend/type2/client/src/page/Home/MainModal.module.css
- frontend/type2/client/src/page/Home/PostDetail.jsx
- frontend/type2/client/src/page/Home/Update_post.jsx
> 게시물 수정삭제등록 팝업
